### ISSUE TITLE
An event with guards should be able to add more guards from right-side panel

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/studio-issues#94]
As soon as a guard is added to an event, this event loses the ability to add more guards from the right-side panel.

### Before adding a guard

![image](https://user-images.githubusercontent.com/12085950/169040777-ae90680c-51b7-4723-9f63-441694f7629a.png)

### After adding a guard

![image](https://user-images.githubusercontent.com/12085950/169040972-4e5dfa94-4516-4ca5-ae53-ad03ce835361.png)

I would normally expect the right-side panel to provide this options since it's offered by the contextual menu.

![image](https://user-images.githubusercontent.com/12085950/169041756-19970b04-72b6-4fc2-92f6-97a217e3c3fc.png)

**Comment by mattpocock** [comment]
This makes sense!

**Comment by davidkpiano** [comment]
Thanks for pointing out a potentially confusing part of the UX:

- An event can only have one guard at most, which is why you can't add more to an event.
- However, a state can have many outgoing events with the same event type, and at least in the canvas, this is visually grouped, but not in the right panel.

cc. @cirephe This is an interesting future design problem to think about. We should have a way of representing (and adding/removing/reordering/etc) "branches" in the right panel:

![CleanShot 2022-05-18 at 08 53 08@2x](https://user-images.githubusercontent.com/1093738/169043483-1d644d22-af8c-4830-a8ee-0048fcd8c0a6.png)

**Comment by davidkpiano** [comment]
Added to Linear: https://linear.app/statelyai/issue/STA-1463/ability-to-add-guarded-transitions-in-panel
